defaults:
  - /llms/ollama@llm

_target_: langchain_graphrag.indexing.entity_extraction.EntityRelationshipExtractor
prompt_builder:
  _target_: langchain_graphrag.indexing.entity_extraction.DefaultEntityExtractionPromptBuilder
  prompt_path: ${paths.prompt_dir}/entity_extraction.txt
output_parser:
  _target_: langchain_graphrag.indexing.entity_extraction.EntityExtractionOutputParser