# @package _global_

defaults:
  - _self_
  - paths: default
  - hydra: default
  - indexing/entity_embedding: default  
  - indexing/relationship_embedding: default  
  - indexing/experiment: null
  
task_name: indexing