# @package _global_

defaults:
  - _self_
  - paths: default
  - hydra: default
  - data: default
  - text_units: default
  - entity_extractor: default  
  - entity_summarizer: default
  - entity_embedding: default
  - relationship_embedding: default
  - indexer: default
  - experiment: null
  
task_name: indexing