_target_: langchain_graphrag.indexing.entity_summarization.EntityRelationshipDescriptionSummarizer
prompt_builder:
  _target_: langchain_graphrag.indexing.entity_summarization.DefaultSummarizeDescriptionPromptBuilder
  prompt_path: ${paths.prompt_dir}/summarize_descriptions.txt

