root_dir: tmp
cache_dir: ${paths.root_dir}/cache 
data_dir: ${paths.root_dir}/input-data/
artifacts_dir: ${paths.root_dir}/input-data/artifacts
prompt_dir: ${paths.root_dir}/prompts
log_dir: ${paths.root_dir}/logs/
output_dir: ${hydra:runtime.output_dir}
work_dir: ${hydra:runtime.cwd}