defaults:
  - /data/default@data_loader
  - /text_units/default@text_unit_extractor
  - /entity_extractor/default@entity_relationship_extractor

_target_: langchain_graphrag.indexing.indexer.Indexer
output_dir: ${paths.artifacts_dir}