_target_: langchain_openai.OpenAIEmbeddings
model: text-embedding-3-small
openai_api_key: ${oc.env:LANGCHAIN_GRAPHRAG_OPENAI_EMBED_API_KEY}
cache:
  _target_: langchain_community.cache.SQLiteCache
  database_path: ${paths.cache_dir}/openai_cache.db