defaults:
  - /data/default@data_loader
  - /text_units/default@text_unit_extractor
  - /entity_extractor/default@er_extractor
  - /entity_summarizer/default@er_description_summarizer
  - /graph_clustering/default@community_detector
  - /entities_table_generator/default@entities_table_generator  
  - /relationships_table_generator/default@relationships_table_generator  
  - /communities_table_generator/default@communities_table_generator  
  - /graph_embedding/default@entities_table_generator.graph_embedding_generator  


_target_: langchain_graphrag.indexing.indexer.Indexer
output_dir: ${paths.artifacts_dir}
  