defaults:
  - /data/default@data_loader
  - /text_units/default@text_unit_extractor
  - /entity_extractor/default@er_extractor
  - /entity_summarizer/default@er_description_summarizer
  - /graph_clustering/default@community_detector
  - /entities_table_generator/default@final_entities_generator  
  - /relationships_table_generator/default@final_relationships_generator  
  - /communities_table_generator/default@final_communities_generator  
  - /graph_embedding/default@final_entities_generator.graph_embedding_generator  


_target_: langchain_graphrag.indexing.indexer.Indexer
output_dir: ${paths.artifacts_dir}
  